# Generated by Django 5.1.2 on 2024-10-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartaodecredito", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartaocredito",
            name="nome_cartao",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
