# Generated by Django 5.1.2 on 2024-10-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
