# Generated by Django 5.1.2 on 2024-10-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0001_initial"),
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True, related_name="favoritado_por", to="carros.car"
            ),
        ),
    ]
