# Generated by Django 5.1.2 on 2024-10-12 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cliente", "0002_remove_cliente_nome_completo_cliente_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="cliente_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="cliente_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
