# Generated by Django 5.1.2 on 2024-10-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_cliente_favoritos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cnh",
            field=models.CharField(default="", max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
