# Generated by Django 5.1.2 on 2024-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_cnh'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
