# Generated by Django 5.1.2 on 2024-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("concluido", "Concluído"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
    ]
