# Generated by Django 5.1.2 on 2024-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0002_agendamento_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_retirada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="horario_devolucao",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="horario_retirada",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="horario",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
