# Generated by Django 5.1.2 on 2024-10-24 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0003_agendamento_data_devolucao_agendamento_data_retirada_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamentos_funcionario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("concluido", "Concluído"),
                    ("cancelado", "Cancelado"),
                    ("em atendimento", "Em Atendimento"),
                ],
                default="pendente",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos_cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
