# Generated by Django 5.1.2 on 2024-10-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0004_agendamento_funcionario_alter_agendamento_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("visita", "Visita"),
                    ("venda", "Venda"),
                    ("aluguel", "Aluguel"),
                ],
                max_length=7,
            ),
        ),
    ]
