# Generated by Django 5.1.2 on 2024-10-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0006_agendamento_data_expiracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("visita", "Visita"),
                    ("reserva", "Reserva"),
                    ("aluguel", "Aluguel"),
                ],
                max_length=7,
            ),
        ),
    ]
