# Generated by Django 5.1.2 on 2024-10-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0008_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="feedbackEnviado",
            field=models.BooleanField(default=False),
        ),
    ]
