# Generated by Django 5.1.2 on 2024-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_remove_feedback_feedbackenviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_agendamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
