# Generated by Django 5.1.2 on 2024-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_agendamento_valor_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
