# Generated by Django 5.1.2 on 2024-11-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_agendamento_valor_pago'),
        ('carros', '0006_remove_car_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.car'),
        ),
    ]
