# Generated by Django 5.1.2 on 2024-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0002_car_is_reserved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="image_url",
        ),
        migrations.AddField(
            model_name="car",
            name="image_url_1",
            field=models.URLField(default="", verbose_name="URL da Imagem Principal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="image_url_2",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL da Segunda Imagem"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="image_url_3",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL da Terceira Imagem"
            ),
        ),
    ]
