# Generated by Django 5.1.2 on 2024-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0004_car_discount_percentage_car_is_discounted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="is_discounted",
        ),
        migrations.AddField(
            model_name="car",
            name="is_discounted_rent",
            field=models.BooleanField(
                default=False, verbose_name="Desconto Aplicado no Aluguel"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="is_discounted_sale",
            field=models.BooleanField(
                default=False, verbose_name="Desconto Aplicado na Venda"
            ),
        ),
    ]
