# Generated by Django 5.1.2 on 2024-11-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0005_remove_car_is_discounted_car_is_discounted_rent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="discount_percentage",
        ),
        migrations.AddField(
            model_name="car",
            name="discount_percentage_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Porcentagem de Desconto no Aluguel",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="discount_percentage_sale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Porcentagem de Desconto na Venda",
            ),
        ),
    ]
